clean up

diff --git a/.github/actions/setup-bird-bench/action.yml b/.github/actions/setup-bird-bench/action.yml
--- a/.github/actions/setup-bird-bench/action.yml
+++ b/.github/actions/setup-bird-bench/action.yml
@@ -57,8 +57,6 @@ runs:
         sudo mkdir -p /opt/spiced/data
         sudo chown runner:runner /opt/spiced/data
 
-        ls -l "$BIRD_BENCH_DIR"
-
         jq -c --arg db "$BIRD_BENCH_DATASET" \
           '.[] | select(.db_id == $db) | { sql: .SQL, question: .question }' "$BIRD_BENCH_DIR/dev.json" \
           > /opt/spiced/data/queryset.json
@@ -66,13 +64,13 @@ runs:
         mv "$BIRD_BENCH_DIR" "${{ inputs.data_directory }}"
 
         DATASET_SPICEPOD="${{ inputs.data_directory }}dev_20240627/spicepods/$BIRD_BENCH_DATASET/spicepod.yaml"
+        if [ ! -f "$DATASET_SPICEPOD" ]; then
+          echo "Error: Spicepod file not found at $DATASET_SPICEPOD"
+          exit 1
+        fi
 
         sudo sed -i \
           's|from: file:\./dev_databases/|from: file:./data/dev_databases/|g' "$DATASET_SPICEPOD"
 
         # Output DATASET_SPICEPOD from action
         echo "spicepod_dependency=$DATASET_SPICEPOD" >> "$GITHUB_OUTPUT"
-
-        # Verify it was written
-        echo "Contents of GITHUB_OUTPUT:"
-        cat "$GITHUB_OUTPUT"
diff --git a/.github/workflows/testoperator_run_texttosql.yml b/.github/workflows/testoperator_run_texttosql.yml
--- a/.github/workflows/testoperator_run_texttosql.yml
+++ b/.github/workflows/testoperator_run_texttosql.yml
@@ -33,7 +33,7 @@ on:
           - 'bird-bench-small[california_schools]'
           - 'bird-bench-small[card_games]'
           - 'bird-bench-small[community]'
-          - 'bird-bench-small[credit_card_specializing]'
+          - 'bird-bench-small[debit_card_specializing]'
           - 'bird-bench-small[european_football2]'
           - 'bird-bench-small[financial]'
           - 'bird-bench-small[formula1]'
@@ -101,10 +101,12 @@ jobs:
 
       - name: Validate queryset inputs
         run: |
-          if [ -n "${{ github.event.inputs.queryset }}" ] && [ -n "${{ github.event.inputs.queryset_file }}" ] && [ -n "${{ github.event.inputs.benchmark_queryset }}" ]; then
-            echo "Error: Only one of 'queryset', 'queryset_file' or 'benchmark_queryset' can be provided"
-            exit 1
-          fi
+          if ([ -n "${{ github.event.inputs.queryset }}" ] && [ -n "${{ github.event.inputs.queryset_file }}" ]) || \
+              ([ -n "${{ github.event.inputs.queryset }}" ] && [ -n "${{ github.event.inputs.benchmark_queryset }}" ]) || \
+              ([ -n "${{ github.event.inputs.queryset_file }}" ] && [ -n "${{ github.event.inputs.benchmark_queryset }}" ]); then
+              echo "Error: Only one of 'queryset', 'queryset_file' or 'benchmark_queryset' can be provided"
+              exit 1
+            fi
 
           if [ -z "${{ github.event.inputs.queryset }}" ] && [ -z "${{ github.event.inputs.queryset_file }}" ] && [ -z "${{ github.event.inputs.benchmark_queryset }}" ]; then
             echo "Error: Either 'queryset', 'queryset_file' or 'benchmark_queryset' must be provided"
