WIP

diff --git a/.github/workflows/e2e_test_ci.yml b/.github/workflows/e2e_test_ci.yml
--- a/.github/workflows/e2e_test_ci.yml
+++ b/.github/workflows/e2e_test_ci.yml
@@ -5,15 +5,18 @@ on:
     branches:
       - trunk
       - release-*
-  
-  # pull_request:
-  #   branches:
-  #     - trunk
+
+  pull_request:
+    branches:
+      - trunk
 
   workflow_dispatch:
 
 jobs:
   build:
+    # WIP
+    if: false
+
     name: Build ${{ matrix.name }} binaries
     runs-on: ${{ matrix.runner }}
     env:
@@ -29,16 +32,17 @@ jobs:
             target_os: linux
             target_arch: x86_64
             target_arch_go: amd64
-          - name: macOS aarch64 (Apple Silicon)
-            runner: macos-14
-            target_os: darwin
-            target_arch: aarch64
-            target_arch_go: arm64
-          - name: macOS x64 (Intel)
-            runner: macos-12
-            target_os: darwin
-            target_arch: x86_64
-            target_arch_go: amd64
+          # WIP
+          # - name: macOS aarch64 (Apple Silicon)
+          #   runner: macos-14
+          #   target_os: darwin
+          #   target_arch: aarch64
+          #   target_arch_go: arm64
+          # - name: macOS x64 (Intel)
+          #   runner: macos-12
+          #   target_os: darwin
+          #   target_arch: x86_64
+          #   target_arch_go: amd64
           # - name: Windows x64
           #   runner: rust-windows-x64
           #   target_os: windows
@@ -138,6 +142,9 @@ jobs:
     runs-on: ${{ matrix.runner }}
     needs: build
 
+    # WIP
+    if: false
+
     strategy:
       fail-fast: false
       matrix:
@@ -218,7 +225,6 @@ jobs:
             echo "Unexpected response: $response, expected 1 dataset but received $length"
             exit 1
           fi
-          
 
       - name: Check taxi_trips table exists
         working-directory: test_app
@@ -234,7 +240,7 @@ jobs:
             echo "Unexpected response: table 'taxi_trips' does not exist."
             exit 1
           fi
-    
+
       - name: Run Flight SQL query
         working-directory: test_app
         run: |
@@ -244,11 +250,14 @@ jobs:
             echo "Unexpected response from spice sql, failed to perform test query: $sql_output"
             exit 1
           fi
-        
+
   test_quickstart_spiceai:
     name: "E2E Test: SpiceAI quickstart, using ${{ matrix.target_os }}-${{ matrix.target_arch }}"
     runs-on: ${{ matrix.runner }}
     needs: build
+
+    # WIP
+    if: false
 
     strategy:
       fail-fast: false
@@ -343,7 +352,7 @@ jobs:
             echo "Unexpected response: table 'taxi_trips' does not exist."
             exit 1
           fi
-    
+
       - name: Run Flight SQL query
         working-directory: test_app
         run: |
@@ -353,3 +362,127 @@ jobs:
             echo "Unexpected response from spice sql, failed to perform test query: $sql_output"
             exit 1
           fi
+
+  test_quickstart_data_posstgres:
+    name: "E2E Test: SpiceAI quickstart, using ${{ matrix.target_os }}-${{ matrix.target_arch }}"
+    runs-on: ${{ matrix.runner }}
+    # needs: build
+
+    services:
+      image: postgres:16
+      env:
+        POSTGRES_USER: postgres
+        POSTGRES_PASSWORD: postgres
+        POSTGRES_DB: testdb
+      ports: 5432:5432
+
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - name: Linux x64
+            runner: ubuntu-latest
+            target_os: linux
+            target_arch: x86_64
+            target_arch_go: amd64
+          # - name: macOS aarch64 (Apple Silicon)
+          #   runner: macos-14
+          #   target_os: darwin
+          #   target_arch: aarch64
+          #   target_arch_go: arm64
+          # - name: macOS x64 (Intel)
+          #   runner: macos-12
+          #   target_os: darwin
+          #   target_arch: x86_64
+          #   target_arch_go: amd64
+          # - name: Windows x64
+          #   runner: rust-windows-x64
+          #   target_os: windows
+          #   target_arch: x86_64
+          #   target_arch_go: amd64
+
+    steps:
+      - name: test postgres
+        run: |
+          psql -h localhost -U postgres -c "CREATE DATABASE testdb;"
+          psql -h localhost -U postgres -d testdb -c "CREATE TABLE test_table (id SERIAL PRIMARY KEY, name VARCHAR(100));"
+          psql -h localhost -U postgres -d testdb -c "INSERT INTO test_table (name) VALUES ('test');"
+          psql -h localhost -U postgres -d testdb -c "SELECT * FROM test_table;"
+
+      # - name: download artifacts - build_${{ matrix.target_os }}_${{ matrix.target_arch }}
+      #   uses: actions/download-artifact@v4
+      #   with:
+      #     name: build_${{ matrix.target_os }}_${{ matrix.target_arch }}
+      #     path: ./build
+
+      # - name: Install spice
+      #   run: |
+      #     chmod +x ./build/spice
+      #     chmod +x ./build/spiced
+      #     echo "$GITHUB_WORKSPACE/build" >> $GITHUB_PATH
+
+      # - name: Check spice version
+      #   run: spice version
+
+      # - name: Init spice app
+      #   run: |
+      #     spice init test_app
+
+      # - name: Spice dataset configure
+      #   working-directory: test_app
+      #   run: |
+      #     echo -e "eth_recent_blocks\neth recent logs\nspice.ai/eth.recent_blocks\ny" | spice dataset configure
+      #     # configure env secret store
+      #     echo -e "secrets:\n  store: env\n" >> spicepod.yaml
+      #     cat spicepod.yaml
+
+      # - name: Start spice runtime
+      #   env:
+      #     SPICE_SECRET_SPICEAI_KEY: ${{ secrets.SPICE_SECRET_SPICEAI_KEY }}
+      #   working-directory: test_app
+      #   run: |
+      #     spice run &
+      #       # time to initialize added dataset
+      #     sleep 5
+
+      # - name: Wait for Spice runtime healthy
+      #   working-directory: test_app
+      #   timeout-minutes: 1
+      #   run: |
+      #     while [[ "$(curl -s http://localhost:3000/health)" != "ok" ]]; do sleep 1; done
+
+      # - name: Check datasets
+      #   working-directory: test_app
+      #   run: |
+      #     response=$(curl http://localhost:3000/v1/datasets)
+      #     echo $response | jq
+      #     length=$(echo $response | jq 'if type=="array" then length else empty end')
+      #     if [[ $length -ne 1 ]]; then
+      #       echo "Unexpected response: $response, expected 1 dataset but received $length"
+      #       exit 1
+      #     fi
+
+      # - name: Check eth_recent_blocks table exists
+      #   working-directory: test_app
+      #   run: |
+      #     response=$(curl -X POST \
+      #       -H "Content-Type: text/plain" \
+      #       -d "show tables;" \
+      #       http://localhost:3000/v1/sql
+      #     )
+      #     echo $response | jq
+      #     table_exists=$(echo $response | jq '[.[] | select(.table_name == "eth_recent_blocks")]' | jq 'length')
+      #     if [[ $table_exists -eq 0 ]]; then
+      #       echo "Unexpected response: table 'taxi_trips' does not exist."
+      #       exit 1
+      #     fi
+
+      # - name: Run Flight SQL query
+      #   working-directory: test_app
+      #   run: |
+      #     sql_output=$(echo "select * from eth_recent_blocks limit 10;" | spice sql)
+      #     echo "$sql_output"
+      #     if [[ $sql_output == *"error"* ]] || [[ $sql_output == *"not found"* ]]; then
+      #       echo "Unexpected response from spice sql, failed to perform test query: $sql_output"
+      #       exit 1
+      #     fi
