WIP

diff --git a/.github/workflows/e2e_test_ci.yml b/.github/workflows/e2e_test_ci.yml
--- a/.github/workflows/e2e_test_ci.yml
+++ b/.github/workflows/e2e_test_ci.yml
@@ -46,7 +46,7 @@ jobs:
                 target_arch: "x86_64",
                 target_arch_go: "amd64"
               }
-            ];
+            ].slice(0, 1);
       - name: Get result
         run: echo '${{ steps.setup-build-matrix.outputs.result }}'
 
@@ -75,17 +75,7 @@ jobs:
                 target_arch: "x86_64",
                 target_arch_go: "amd64"
               }
-            ];
-        # ÷÷run: |
-        # echo "matrix=" >> "$GITHUB_OUTPUT"
-        # run: |
-        #   echo "::set-output name=matrix::${{ toJson({
-        #     "name": ["Linux x64", "macOS aarch64 (Apple Silicon)", "macOS x64 (Intel)", "Windows x64"],
-        #     "runner": ["ubuntu-latest", "macos-14", "macos-12", "rust-windows-x64"],
-        #     "target_os": ["linux", "darwin", "darwin", "windows"],
-        #     "target_arch": ["x86_64", "aarch64", "x86_64", "x86_64"],
-        #     "target_arch_go": ["amd64", "arm64", "amd64", "amd64"]
-        #   }) }}"
+            ].slice(0, 1);
 
   build:
     name: Build ${{ matrix.object.name }} binaries
@@ -99,27 +89,6 @@ jobs:
     strategy:
       matrix:
         object: ${{ fromJson(needs.setup-matrix.outputs.matrix_build) }}
-        # include:
-        #   - name: Linux x64
-        #     runner: rust
-        #     target_os: linux
-        #     target_arch: x86_64
-        #     target_arch_go: amd64
-        #   - name: macOS aarch64 (Apple Silicon)
-        #     runner: macos-14
-        #     target_os: darwin
-        #     target_arch: aarch64
-        #     target_arch_go: arm64
-        #   - name: macOS x64 (Intel)
-        #     runner: macos-12
-        #     target_os: darwin
-        #     target_arch: x86_64
-        #     target_arch_go: amd64
-        # - name: Windows x64
-        #   runner: rust-windows-x64
-        #   target_os: windows
-        #   target_arch: x86_64
-        #   target_arch_go: amd64
 
     steps:
       - uses: actions/checkout@v3
@@ -217,31 +186,8 @@ jobs:
       - setup-matrix
 
     strategy:
-      fail-fast: false
       matrix:
         object: ${{ fromJson(needs.setup-matrix.outputs.matrix_test) }}
-
-        # include:
-        #   - name: Linux x64
-        #     runner: ubuntu-latest
-        #     target_os: linux
-        #     target_arch: x86_64
-        #     target_arch_go: amd64
-        #   - name: macOS aarch64 (Apple Silicon)
-        #     runner: macos-14
-        #     target_os: darwin
-        #     target_arch: aarch64
-        #     target_arch_go: arm64
-        #   - name: macOS x64 (Intel)
-        #     runner: macos-12
-        #     target_os: darwin
-        #     target_arch: x86_64
-        #     target_arch_go: amd64
-        # - name: Windows x64
-        #   runner: rust-windows-x64
-        #   target_os: windows
-        #   target_arch: x86_64
-        #   target_arch_go: amd64
 
     steps:
       - name: download artifacts - build_${{ matrix.target_os }}_${{ matrix.target_arch }}
@@ -326,117 +272,98 @@ jobs:
             exit 1
           fi
 
-  # test_quickstart_spiceai:
-  #   name: "E2E Test: SpiceAI quickstart, using ${{ matrix.target_os }}-${{ matrix.target_arch }}"
-  #   runs-on: ${{ matrix.runner }}
-  #   needs: build
+  test_quickstart_spiceai:
+    name: "E2E Test: SpiceAI quickstart, using ${{ matrix.object.target_os }}-${{ matrix.object.target_arch }}"
+    runs-on: ${{ matrix.object.runner }}
+    needs:
+      - build
+      - setup-matrix
 
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       include:
-  #         - name: Linux x64
-  #           runner: ubuntu-latest
-  #           target_os: linux
-  #           target_arch: x86_64
-  #           target_arch_go: amd64
-  #         - name: macOS aarch64 (Apple Silicon)
-  #           runner: macos-14
-  #           target_os: darwin
-  #           target_arch: aarch64
-  #           target_arch_go: arm64
-  #         - name: macOS x64 (Intel)
-  #           runner: macos-12
-  #           target_os: darwin
-  #           target_arch: x86_64
-  #           target_arch_go: amd64
-  #         # - name: Windows x64
-  #         #   runner: rust-windows-x64
-  #         #   target_os: windows
-  #         #   target_arch: x86_64
-  #         #   target_arch_go: amd64
+    strategy:
+      matrix:
+        object: ${{ fromJson(needs.setup-matrix.outputs.matrix_test) }}
 
-  #   steps:
-  #     - name: download artifacts - build_${{ matrix.target_os }}_${{ matrix.target_arch }}
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: build_${{ matrix.target_os }}_${{ matrix.target_arch }}
-  #         path: ./build
+    steps:
+      - name: download artifacts - build_${{ matrix.object.target_os }}_${{ matrix.object.target_arch }}
+        uses: actions/download-artifact@v4
+        with:
+          name: build_${{ matrix.object.target_os }}_${{ matrix.object.target_arch }}
+          path: ./build
 
-  #     - name: Install spice
-  #       run: |
-  #         chmod +x ./build/spice
-  #         chmod +x ./build/spiced
-  #         mkdir -p "$HOME/.spice/bin"
-  #         mv ./build/spice "$HOME/.spice/bin"
-  #         mv ./build/spiced "$HOME/.spice/bin"
-  #         echo "$HOME/.spice/bin" >> $GITHUB_PATH
+      - name: Install spice
+        run: |
+          chmod +x ./build/spice
+          chmod +x ./build/spiced
+          mkdir -p "$HOME/.spice/bin"
+          mv ./build/spice "$HOME/.spice/bin"
+          mv ./build/spiced "$HOME/.spice/bin"
+          echo "$HOME/.spice/bin" >> $GITHUB_PATH
 
-  #     - name: Check spice version
-  #       run: spice version
+      - name: Check spice version
+        run: spice version
 
-  #     - name: Init spice app
-  #       run: |
-  #         spice init test_app
+      - name: Init spice app
+        run: |
+          spice init test_app
 
-  #     - name: Spice dataset configure
-  #       working-directory: test_app
-  #       run: |
-  #         echo -e "eth_recent_blocks\neth recent logs\nspice.ai/eth.recent_blocks\ny" | spice dataset configure
-  #         # configure env secret store
-  #         echo -e "secrets:\n  store: env\n" >> spicepod.yaml
-  #         cat spicepod.yaml
+      - name: Spice dataset configure
+        working-directory: test_app
+        run: |
+          echo -e "eth_recent_blocks\neth recent logs\nspice.ai/eth.recent_blocks\ny" | spice dataset configure
+          # configure env secret store
+          echo -e "secrets:\n  store: env\n" >> spicepod.yaml
+          cat spicepod.yaml
 
-  #     - name: Start spice runtime
-  #       env:
-  #         SPICE_SECRET_SPICEAI_KEY: ${{ secrets.SPICE_SECRET_SPICEAI_KEY }}
-  #       working-directory: test_app
-  #       run: |
-  #         spice run &
-  #          # time to initialize added dataset
-  #         sleep 5
+      - name: Start spice runtime
+        env:
+          SPICE_SECRET_SPICEAI_KEY: ${{ secrets.SPICE_SECRET_SPICEAI_KEY }}
+        working-directory: test_app
+        run: |
+          spice run &
+           # time to initialize added dataset
+          sleep 5
 
-  #     - name: Wait for Spice runtime healthy
-  #       working-directory: test_app
-  #       timeout-minutes: 1
-  #       run: |
-  #         while [[ "$(curl -s http://localhost:3000/health)" != "ok" ]]; do sleep 1; done
+      - name: Wait for Spice runtime healthy
+        working-directory: test_app
+        timeout-minutes: 1
+        run: |
+          while [[ "$(curl -s http://localhost:3000/health)" != "ok" ]]; do sleep 1; done
 
-  #     - name: Check datasets
-  #       working-directory: test_app
-  #       run: |
-  #         response=$(curl http://localhost:3000/v1/datasets)
-  #         echo $response | jq
-  #         length=$(echo $response | jq 'if type=="array" then length else empty end')
-  #         if [[ $length -ne 1 ]]; then
-  #           echo "Unexpected response: $response, expected 1 dataset but received $length"
-  #           exit 1
-  #         fi
+      - name: Check datasets
+        working-directory: test_app
+        run: |
+          response=$(curl http://localhost:3000/v1/datasets)
+          echo $response | jq
+          length=$(echo $response | jq 'if type=="array" then length else empty end')
+          if [[ $length -ne 1 ]]; then
+            echo "Unexpected response: $response, expected 1 dataset but received $length"
+            exit 1
+          fi
 
-  #     - name: Check eth_recent_blocks table exists
-  #       working-directory: test_app
-  #       run: |
-  #         response=$(curl -X POST \
-  #           -H "Content-Type: text/plain" \
-  #           -d "show tables;" \
-  #           http://localhost:3000/v1/sql
-  #         )
-  #         echo $response | jq
-  #         table_exists=$(echo $response | jq '[.[] | select(.table_name == "eth_recent_blocks")]' | jq 'length')
-  #         if [[ $table_exists -eq 0 ]]; then
-  #           echo "Unexpected response: table 'eth_recent_blocks' does not exist."
-  #           exit 1
-  #         fi
+      - name: Check eth_recent_blocks table exists
+        working-directory: test_app
+        run: |
+          response=$(curl -X POST \
+            -H "Content-Type: text/plain" \
+            -d "show tables;" \
+            http://localhost:3000/v1/sql
+          )
+          echo $response | jq
+          table_exists=$(echo $response | jq '[.[] | select(.table_name == "eth_recent_blocks")]' | jq 'length')
+          if [[ $table_exists -eq 0 ]]; then
+            echo "Unexpected response: table 'eth_recent_blocks' does not exist."
+            exit 1
+          fi
 
-  #     - name: Run Flight SQL query
-  #       working-directory: test_app
-  #       run: |
-  #         sql_output=$(echo "select * from eth_recent_blocks limit 10;" | spice sql)
-  #         echo "$sql_output"
-  #         if [[ $sql_output == *"error"* ]] || [[ $sql_output == *"not found"* ]]; then
-  #           echo "Unexpected response from spice sql, failed to perform test query: $sql_output"
-  #           exit 1
-  #         fi
+      - name: Run Flight SQL query
+        working-directory: test_app
+        run: |
+          sql_output=$(echo "select * from eth_recent_blocks limit 10;" | spice sql)
+          echo "$sql_output"
+          if [[ $sql_output == *"error"* ]] || [[ $sql_output == *"not found"* ]]; then
+            echo "Unexpected response from spice sql, failed to perform test query: $sql_output"
+            exit 1
+          fi
 
   # test_quickstart_data_postgres:
   #   name: "E2E Test: SpiceAI Postgres quickstart, using ${{ matrix.target_os }}-${{ matrix.target_arch }}"
