don't fail cargo test if we're updating snapshots

diff --git a/.github/workflows/integration_search.yml b/.github/workflows/integration_search.yml
--- a/.github/workflows/integration_search.yml
+++ b/.github/workflows/integration_search.yml
@@ -55,7 +55,14 @@ jobs:
             echo "Error: OpenAI API key is not defined."
             exit 1
           fi
-          cargo test --test integration_models -p runtime  --features models,metal,s3_vectors,kafka,duckdb,extended_tests -- search
+          cargo test --test integration_models -p runtime  --features models,metal,s3_vectors,kafka,duckdb,extended_tests -- search || {
+            if [ "$INSTA_UPDATE" == "always" ]; then
+              echo "Warning: Tests failed but INSTA_UPDATE is enabled. Continuing."
+              exit 0
+            else
+              exit 1
+            fi
+          }
 
       - name: Push snapshots to branch
         if: github.event.inputs.update_snapshots == 'always' || github.event_name == 'schedule'
