check for SPICE_PERPLEXITY_AUTH_TOKEN

diff --git a/.github/workflows/integration_llms.yml b/.github/workflows/integration_llms.yml
--- a/.github/workflows/integration_llms.yml
+++ b/.github/workflows/integration_llms.yml
@@ -127,6 +127,10 @@ jobs:
               echo "Error: xAI API key is not defined."
               exit 1
             fi
+            if [ -z "$SPICE_PERPLEXITY_AUTH_TOKEN" ]; then
+              echo "Error: Perplexity API key is not defined."
+              exit 1
+            fi
           fi
           # `--test-threads` to reduce possible rate limiting/ connection issues for hosted models.
           INSTA_WORKSPACE_ROOT="${PWD}" CARGO_MANIFEST_DIR="${PWD}" ./integration_test/llms_integration_test --nocapture -- --test-threads=2
