Fix .env in '.github/workflows/integration_llms.yml' (#3686)
* change integration_models.yml

* fix actions

* Update integration_llms.yml

diff --git a/.github/workflows/integration_llms.yml b/.github/workflows/integration_llms.yml
--- a/.github/workflows/integration_llms.yml
+++ b/.github/workflows/integration_llms.yml
@@ -71,10 +71,22 @@ jobs:
         run: |
           chmod +x ./integration_test/llms_integration_test
 
-      - name: Set up Anthropic API Key
+      - name: Set up .env file
         run: |
-          echo 'SPICE_ANTHROPIC_API_KEY="${{ secrets.SPICE_SECRET_ANTHROPIC_API_KEY }}"\nSPICE_OPENAI_API_KEY="${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}"' > .env
+          echo 'SPICE_OPENAI_API_KEY="${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}"' > .env
+          echo 'SPICE_ANTHROPIC_API_KEY="${{ secrets.SPICE_SECRET_ANTHROPIC_API_KEY }}"' >> .env
 
       - name: Run integration test
+        env:
+          SPICE_SECRET_OPENAI_API_KEY: ${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}
+          SPICE_SECRET_ANTHROPIC_API_KEY: ${{ secrets.SPICE_SECRET_ANTHROPIC_API_KEY }}
         run: |
+          if [ -z "$SPICE_SECRET_OPENAI_API_KEY" ] ; then
+            echo "Error: OpenAI API key is not defined."
+            exit 1
+          fi
+          if [ -z "$SPICE_SECRET_ANTHROPIC_API_KEY" ] ; then
+            echo "Error: Anthropic API key is not defined."
+            exit 1
+          fi
           INSTA_WORKSPACE_ROOT="${PWD}" CARGO_MANIFEST_DIR="${PWD}" ./integration_test/llms_integration_test --nocapture
