revert: Remove .github workflow changes

diff --git a/.github/workflows/integration_search.yml b/.github/workflows/integration_search.yml
--- a/.github/workflows/integration_search.yml
+++ b/.github/workflows/integration_search.yml
@@ -58,12 +58,17 @@ jobs:
             echo "Error: OpenAI API key is not defined."
             exit 1
           fi
-          cargo test --test integration_models -p runtime --features models,metal,s3_vectors,kafka,duckdb,extended_tests -- search
+          cargo test --test integration_models -p runtime  --features models,metal,s3_vectors,kafka,duckdb,extended_tests -- search || {
+            if [ "$INSTA_UPDATE" == "always" ]; then
+              echo "Warning: Tests failed but INSTA_UPDATE is enabled. Continuing."
+              exit 0
+            else
+              exit 1
+            fi
+          }
 
       - name: Push snapshots to branch
-        # `cargo test` will fail if snapshot changes are needed. Always attempt
-        #  to make PR if 'always' update snapshots.
-        if: ${{ always() && (github.event.inputs.update_snapshots == 'always' || github.event_name == 'schedule') }}
+        if: github.event.inputs.update_snapshots == 'always' || github.event_name == 'schedule'
         uses: ./.github/actions/push-snap-changes
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
