add california schools bird-bench small

diff --git a/.github/workflows/testoperator_run_texttosql.yml b/.github/workflows/testoperator_run_texttosql.yml
--- a/.github/workflows/testoperator_run_texttosql.yml
+++ b/.github/workflows/testoperator_run_texttosql.yml
@@ -23,6 +23,12 @@ on:
         description: 'The queryset to use for the text-to-sql benchmark'
         required: false
         type: string
+      benchmark_queryset:
+        description: 'Predefined (possibly external) queryset to setup and use'
+        required: false
+        type: choice
+        options:
+          - 'bird-bench-small'
       runner_type:
         description: 'Runner type'
         required: true
@@ -84,12 +90,13 @@ jobs:
 
       - name: Validate queryset inputs
         run: |
-          if [ -n "${{ github.event.inputs.queryset }}" ] && [ -n "${{ github.event.inputs.queryset_file }}" ]; then
-            echo "Error: Only one of 'queryset' or 'queryset_file' should be provided, not both"
+          if [ -n "${{ github.event.inputs.queryset }}" ] && [ -n "${{ github.event.inputs.queryset_file }}" ] && [ -n "${{ github.event.inputs.benchmark_queryset }}" ]; then
+            echo "Error: Only one of 'queryset', 'queryset_file' or 'benchmark_queryset' can be provided"
             exit 1
           fi
-          if [ -z "${{ github.event.inputs.queryset }}" ] && [ -z "${{ github.event.inputs.queryset_file }}" ]; then
-            echo "Error: Either 'queryset' or 'queryset_file' must be provided"
+
+          if [ -z "${{ github.event.inputs.queryset }}" ] && [ -z "${{ github.event.inputs.queryset_file }}" ] && [ -z "${{ github.event.inputs.benchmark_queryset }}" ]; then
+            echo "Error: Either 'queryset', 'queryset_file' or 'benchmark_queryset' must be provided"
             exit 1
           fi
 
@@ -100,18 +107,34 @@ jobs:
           SPICEPOD_FILENAME=$(basename $SPICEPOD_PATH)
           echo "SPICEPOD_FILENAME=${SPICEPOD_FILENAME}" >> $GITHUB_OUTPUT
 
+      - name: Setup benchmark queryset data
+        if: ${{ github.event.inputs.benchmark_queryset != '' }}
+        uses: ./.github/actions/setup-testoperator-data
+        with:
+          query_set: ${{ github.event.inputs.benchmark_queryset }}
+
       - name: Run the benchmark test - ${{ steps.extract_spicepod_filename.outputs.SPICEPOD_FILENAME }}
         run: |
           rm -rf .spice/data
           QUERYSET_ARG=""
+          SPICEPOD_DEPENDENCY=""
           if [ -n "${{ github.event.inputs.queryset_file }}" ]; then
             QUERYSET_ARG="--queryset-file ${{ github.event.inputs.queryset_file }}"
           elif [ -n "${{ github.event.inputs.queryset }}" ]; then
             QUERYSET_ARG="--queryset ${{ github.event.inputs.queryset }}"
+          elif [ -n "${{ github.event.inputs.benchmark_queryset }}" ]; then
+            QUERYSET_ARG='--queryset-file /opt/spiced/data/queryset.json'
+            SPICEPOD_DEPENDENCY="--spicepod-dependencies /opt/spiced/data/spicepods/california_schools"
+          else
+            echo "Error: No valid queryset input provided"
+            exit 1
           fi
+
           testoperator run text-to-sql \
             --ready-wait 1800 \
             $QUERYSET_ARG \
+            $SPICEPOD_DEPENDENCY \
+            -d /opt/spiced/data \
             --model ${{ github.event.inputs.model_name }} \
             -p "${{ github.event.inputs.spicepod_path }}"
         env:
