Build and run spice

diff --git a/.github/workflows/tpch_benchmark.yml b/.github/workflows/tpch_benchmark.yml
--- a/.github/workflows/tpch_benchmark.yml
+++ b/.github/workflows/tpch_benchmark.yml
@@ -1,11 +1,6 @@
 name: TPC-H Benchmark
 
 on:
-  # push:
-  #   branches:
-  #     - trunk
-  #     - release-*
-
   pull_request:
     branches:
       - trunk
@@ -14,7 +9,7 @@ on:
 
 jobs:
   build:
-    if: false
+    # if: false
     name: Build ${{ matrix.name }} binaries
     runs-on: ${{ matrix.runner }}
     env:
@@ -137,7 +132,7 @@ jobs:
   tpc_h_benchmark:
     name: "Run TPC-H Benchmark on ${{ matrix.target_os }}-${{ matrix.target_arch }}"
     runs-on: ${{ matrix.runner }}
-    #needs: build
+    needs: build
 
     strategy:
       fail-fast: false
@@ -167,6 +162,24 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
+
+      - name: download artifacts - build_${{ matrix.target_os }}_${{ matrix.target_arch }}
+        uses: actions/download-artifact@v4
+        with:
+          name: build_${{ matrix.target_os }}_${{ matrix.target_arch }}
+          path: ./build
+
+      - name: Install spice
+        run: |
+          chmod +x ./build/spice
+          chmod +x ./build/spiced
+          mkdir -p "$HOME/.spice/bin"
+          mv ./build/spice "$HOME/.spice/bin"
+          mv ./build/spiced "$HOME/.spice/bin"
+          echo "$HOME/.spice/bin" >> $GITHUB_PATH
+
+      - name: Check spice version
+        run: spice version
 
       - name: Install PostgreSQL (Linux)
         if: matrix.target_os == 'linux'
@@ -222,85 +235,24 @@ jobs:
         run: |
           make tpch-run-pq
 
-      # - name: download artifacts - build_${{ matrix.target_os }}_${{ matrix.target_arch }}
-      #   uses: actions/download-artifact@v4
-      #   with:
-      #     name: build_${{ matrix.target_os }}_${{ matrix.target_arch }}
-      #     path: ./build
 
-      # - name: Install spice
-      #   run: |
-      #     chmod +x ./build/spice
-      #     chmod +x ./build/spiced
-      #     mkdir -p "$HOME/.spice/bin"
-      #     mv ./build/spice "$HOME/.spice/bin"
-      #     mv ./build/spiced "$HOME/.spice/bin"
-      #     echo "$HOME/.spice/bin" >> $GITHUB_PATH
+      - name: Start spice runtime
+        working-directory: ./test/tpch/tpch-spicepod
+        run: |
+          spice run &
+            # time to initialize added datasets
+          sleep 5
 
-      # - name: Check spice version
-      #   run: spice version
+      - name: Wait for Spice runtime healthy
+        timeout-minutes: 1
+        run: |
+          while [[ "$(curl -s http://localhost:3000/health)" != "ok" ]]; do sleep 1; done
 
-      # - name: Init spice app
-      #   run: |
-      #     spice init test_app
-
-      # - name: Spice dataset configure
-      #   working-directory: test_app
-      #   run: |
-      #     echo -e "eth_recent_blocks\neth recent blocks\npostgres:eth_recent_blocks\ny" | spice dataset configure
-      #     # configure pg credentials
-      #     echo -e "params:\n  pg_host: localhost\n  pg_port: 5432\n  pg_db: testdb\n  pg_user: postgres\n  pg_pass_key: password" >> ./datasets/eth_recent_blocks/dataset.yaml
-      #     # configure env secret store
-      #     echo -e "secrets:\n  store: env\n" >> spicepod.yaml
-      #     cat spicepod.yaml
-
-      # - name: Start spice runtime
-      #   env:
-      #     SPICE_SECRET_POSTGRES_PASSWORD: postgres
-      #   working-directory: test_app
-      #   run: |
-      #     spice run &
-      #       # time to initialize added dataset
-      #     sleep 5
-
-      # - name: Wait for Spice runtime healthy
-      #   working-directory: test_app
-      #   timeout-minutes: 1
-      #   run: |
-      #     while [[ "$(curl -s http://localhost:3000/health)" != "ok" ]]; do sleep 1; done
-
-      # - name: Check datasets
-      #   working-directory: test_app
-      #   run: |
-      #     response=$(curl http://localhost:3000/v1/datasets)
-      #     echo $response | jq
-      #     length=$(echo $response | jq 'if type=="array" then length else empty end')
-      #     if [[ $length -ne 1 ]]; then
-      #       echo "Unexpected response: $response, expected 1 dataset but received $length"
-      #       exit 1
-      #     fi
-
-      # - name: Check eth_recent_blocks table exists
-      #   working-directory: test_app
-      #   run: |
-      #     response=$(curl -X POST \
-      #       -H "Content-Type: text/plain" \
-      #       -d "show tables;" \
-      #       http://localhost:3000/v1/sql
-      #     )
-      #     echo $response | jq
-      #     table_exists=$(echo $response | jq '[.[] | select(.table_name == "eth_recent_blocks")]' | jq 'length')
-      #     if [[ $table_exists -eq 0 ]]; then
-      #       echo "Unexpected response: table 'eth_recent_blocks' does not exist."
-      #       exit 1
-      #     fi
-
-      # - name: Run Flight SQL query
-      #   working-directory: test_app
-      #   run: |
-      #     sql_output=$(echo "select * from eth_recent_blocks limit 10;" | spice sql)
-      #     echo "$sql_output"
-      #     if [[ $sql_output == *"error"* ]] || [[ $sql_output == *"not found"* ]]; then
-      #       echo "Unexpected response from spice sql, failed to perform test query: $sql_output"
-      #       exit 1
-      #     fi
+      - name: Run TPC-H queries (Spice)
+        run: |
+          sql_output=$(echo "select * from customer limit 10;" | spice sql)
+          echo "$sql_output"
+          if [[ $sql_output == *"error"* ]] || [[ $sql_output == *"not found"* ]]; then
+            echo "Unexpected response from spice sql, failed to perform test query: $sql_output"
+            exit 1
+          fi
